omero:
  username: "USERNAME_HERE"
  password: "PASSWORD_HERE"
  host: "ucl-hist-omero.cs.ucl.ac.uk"
  port: 4064
  web_base_url: "https://ucl-hist-omero.cs.ucl.ac.uk/webclient/img_detail/"
  project_id: 251
  dataset_id: null  # Set to null if you don't want to restrict by dataset
